# Build stage
FROM maven:3.8.4-openjdk-17 AS build

# Set the working directory
WORKDIR /workspace/app

# Copy the application
COPY . .

# Build the application
RUN ./mvnw package -Pprod

# Runtime stage
FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the built artifact from the build stage
COPY --from=build /workspace/app/target/*.jar app.jar

# Expose the port the app runs on
EXPOSE 8080

# Set environment variables
ENV SPRING_PROFILES_ACTIVE=prod
ENV SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jhipsterTaskApp
ENV SPRING_DATASOURCE_USERNAME=yourUsername
ENV SPRING_DATASOURCE_PASSWORD=yourPassword

# Run the application
CMD ["java", "-jar", "app.jar"]
