name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pipeline:
    name: jhipster pipeline
    runs-on: ubuntu-latest
    if: '!contains(github.event.head_commit.message, "[ci skip]") && !contains(github.event.head_commit.message, "[skip ci]")'
    timeout-minutes: 40
    env:
      NODE_VERSION: 16.x
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      SPRING_JPA_SHOW_SQL: false
      JHI_DISABLE_WEBPACK_LOGS: true

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Debug information
        run: |
          pwd
          ls -la
          java -version
          mvn -version

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run backend tests
        run: ./mvnw clean verify

      - name: Run frontend tests
        run: npm run test

      - name: Package application
        run: ./mvnw package -Pprod -DskipTests

      - name: Build and publish docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./mvnw -ntp jib:build -Djib.to.image=docker.pkg.github.com/${{ github.repository }}/jhipster-task-app:latest -Djib.to.auth.username=${{ github.actor }} -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag docker.pkg.github.com/${{ github.repository }}/jhipster-task-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/jhipster-task-app:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/jhipster-task-app:latest
