name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: |
        cd jhipster-task-app
        chmod +x mvnw
        ./mvnw clean verify -Pprod -DskipTests

    - name: Run tests
      run: |
        cd jhipster-task-app
        ./mvnw test

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: jhipster-task-app/target/surefire-reports

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ watashiWA19 }}
        password: ${{ 339939939}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./jhipster-task-app
        file: ./jhipster-task-app/src/main/docker/Dockerfile.jvm
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          watashiwa19/dvtsk:latest
          watashiwa19/dvtsk:${{ github.sha }}

    - name: Cleanup
      if: always()
      run: |
        cd jhipster-task-app
        ./mvnw clean
        docker image prune -f
