name: Docker Build and Push

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Remove duplicate test classes
      run: |
        cd jhipster-task-app
        rm -rf src/test/java/ipsum

    - name: Make mvnw executable
      run: chmod +x jhipster-task-app/mvnw

    - name: Build with Maven and create Docker image
      run: |
        cd jhipster-task-app
        ./mvnw clean verify -Pprod jib:dockerBuild -DskipTests

    - name: List Docker images
      run: docker images

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Docker image
      run: |
        IMAGE_NAME=$(./mvnw help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
        IMAGE_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
        docker tag ${IMAGE_NAME}:${IMAGE_VERSION} ${{ secrets.DOCKER_HUB_USERNAME }}/${IMAGE_NAME}:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${IMAGE_NAME}:latest
