name: Docker Build and Push

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./jhipster-task-app
        file: ./jhipster-task-app/.devcontainer/Dockerfile
        push: true
        tags: watashiwa19/latestdvtaskimagethelatest:latest001

    - name: Verify Docker image
      run: |
        docker pull watashiwa19/latestdvtaskimagethelatest:latest001
        docker inspect watashiwa19/latestdvtaskimagethelatest:latest001

    - name: Run Docker image and capture logs
      run: |
        docker run -d --name test-container watashiwa19/latestdvtaskimagethelatest:latest001
        sleep 60  # Wait for the application to start
        docker logs test-container

    - name: Debug - Check container status
      run: |
        docker ps -a
        docker top test-container
        docker exec test-container ps aux

    - name: Debug - Check if application is listening on port 8080
      run: |
        docker exec test-container netstat -tuln

    - name: Check application health
      run: |
        docker exec test-container curl -f http://localhost:8080/management/health || (echo "Health check failed" && exit 1)

    - name: Clean up
      run: docker rm -f test-container

    - name: Debug - Docker build logs
      if: failure()
      run: |
        echo "Docker build logs:"
        docker buildx build --progress=plain --load -t watashiwa19/latestdvtaskimagethelatest:latest001 -f ./jhipster-task-app/.devcontainer/Dockerfile ./jhipster-task-app
