name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: dvtask

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build application
      run: |
        cd jhipster-task-app
        chmod +x mvnw
        ./mvnw clean package -Pprod -DskipTests

    - name: Build and push Docker image
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      run: |
        cd jhipster-task-app
        docker build -f src/main/docker/Dockerfile.jvm -t $DOCKER_HUB_USERNAME/$IMAGE_NAME:latest .
        echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
        docker push $DOCKER_HUB_USERNAME/$IMAGE_NAME:latest
