name: CI Pipeline 1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: |
        cd jhipster-task-app
        chmod +x mvnw
        ./mvnw clean package -Pprod -DskipTests

    - name: Run tests
      run: |
        cd jhipster-task-app
        ./mvnw test

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./jhipster-task-app
        file: ./jhipster-task-app/src/main/docker/Dockerfile.jvm
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/dvtsk:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/dvtsk:${{ github.sha }}

    - name: Cleanup
      if: always()
      run: |
        cd jhipster-task-app
        ./mvnw clean
        docker image prune -f
